theme = "awesome-identity"
baseURL = "https://adityagoel.me"
title = "Aditya Goel"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


## Profile Configurations
[params.profile]
  portrait = "images/try.jpg"
  firstname = "Aditya"
  lastname = "Goel"
  title = "Software Engineer and ML Researcher"
  bio = """A Computer Science student and International Scholar at [**UBC**](https://www.cs.ubc.ca/), with a proven track-record in software engineering, infrastructure, and machine learning.

Interned as a software engineer at, [**Shopify**](https://www.shopify.com/), [**Electronic Arts**](https://www.ea.com/) and [**Rivian**](https://rivian.com/). Other experiences include building a [**HFT order matching system**](https://github.com/agoel25/quantaTrader) in C++ and my own [**GPT model**](https://github.com/agoel25/myGPT) in PyTorch from scratch, open source contributions, and teaching the algorithms and data structures course at UBC.

Always looking for the next challenge to grow my skills, please feel free to reach out! 
  """

## Contacts Configurations
[params.contacts]
  email = "agoel25@student.ubc.ca"
  github = "agoel25"
  linkedin = "agoel25"

[params.actions.resume]
  name = "See my Resume"
  url = "./adityagoel.pdf"

## Footer Configurations
[params.footer]
  copyright = "Â© 2025 Aditya Goel"
  poweredBy = false
